let projectContent = [
  {
    id: 0,
    title: "Projet d'intégration",
    description:
      "Projet proposé par mon établissement durant ma formation BTS SIO, durant lequel j'ai découvert le HTML et le CSS",
    date: "Novembre 2020",
    time: "5h",
    buttonText: "En savoir plus",
    group: 'travail en groupe',
    resp: 'Responsive',
    techno: 'HTML / CSS',
    icon: "work",
    image: {
        src1: '/images/integration/1.png',
        src2: '/images/integration/2.png',
        src3: '/images/integration/3.png'
    },
    cardIcon: '/images/integration/icon.png',
  },
  {
    id: 1,
    title: "Portfolio V1",
    description: "Projet développer durant ma première année de BTS SIO, Découverte du PHP / MYSQL pour le backoffice (Back-End)",
    date: "Decembre 2020 - Juin 2022",
    time: "15h",
    buttonText: "En savoir plus",
    group: 'travail individuel',
    resp: 'Responsive',
    techno: 'HTML / CSS / PHP / BOOTSTRAP / SQL',
    icon: "work",
    image: {
        src1: '/images/portfolioV1/1.png',
        src2: '/images/portfolioV1/2.png',
        src3: '/images/portfolioV1/3.png'
    },
    cardIcon: '/images/portfolioV1/icon.png',
  },
  {
    id: 2,
    title: "Bot Discord",
    description: "Un bot Discord développer en JS pour rejoindre des serveurs NFT plus rapidement",
    date: "Novembre 2021",
    time: "3h",
    buttonText: "En savoir plus",
    group: 'travail individuel',
    resp: 'Pas de reponsive',
    techno: 'JS / API DISCORD ',
    icon: "work",
    image: {
        src1: '/images/botjs/1.png',
    },
    cardIcon: '/images/botjs/icon.png',
  },
  {
    id: 3,
    title: "Sandwicherie",
    description: "Projet développer pour la cantine de mon BTS SIO, travail en groupe avec github (J'ai réaliser le formulaire de commande en PHP / SQL) ",
    date: "Mars 2022 - Mai 2022",
    time: "10h",
    buttonText: "En savoir plus",
    group: 'travail en groupe',
    resp: 'Responsive',
    techno: 'HTML / CSS / PHP / BOOTSTRAP / SQL',
    icon: "work",
    image: {
        src1: '/images/sandwicherie/1.png',
        src2: '/images/sandwicherie/2.png',
        src3: '/images/sandwicherie/3.png'
    },
    cardIcon: '/images/sandwicherie/icon.png',
  },
  {
    id: 4,
    title: "Blog React",
    description: "Un blog développer pendant mon apprentisage de React, Utilisation de firebase et axios pour la partie base de données",
    date: "Juillet 2022",
    time: "12h",
    buttonText: "En savoir plus",
    group: 'travail Individuelle',
    resp: 'Responsive',
    techno: 'REACT / FIREBASE',
    icon: "work",
    image: {
        src1: '/images/blog/1.png',
        src2: '/images/blog/2.png',
        src3: '/images/blog/3.png'
    },
    cardIcon: '/images/blog/icon.png',
  },
  {
    id: 5,
    title: "Portfolio v2",
    description: "Deuxième version du portfolio réalisé en react.js afin de vérifié la comprehension des notions acquises en autodidacte",
    date: "Aout 2022",
    time: "20h",
    buttonText: "En savoir plus",
    group: 'travail Individuelle',
    resp: 'Responsive',
    techno: 'REACT',
    icon: "work",
    image: {
        src1: '/images/portfolioV2/1.png',
        src2: '/images/portfolioV2/2.png',
        src3: '/images/portfolioV2/3.png'
    },
    cardIcon: '/images/portfolioV2/icon.png',
  },
  {
    id: 6,
    title: "Bot Sneaky Vampire",
    description: "Un bot réaliser en python / selenium afin d'acheter automatiquement des cartes cadeaux en échange de token (Eth blockchain)",
    date: "Aout 2022",
    time: "20h",
    buttonText: "En savoir plus",
    group: 'travail Individuelle',
    resp: 'Chrome Driver',
    techno: 'Python / Selenium',
    icon: "work",
    image: {
        src1: '/images/portfolioV2/1.png',
        src2: '/images/portfolioV2/2.png',
        src3: '/images/portfolioV2/3.png'
    },
    cardIcon: '/images/sneaky/icon.png',
  },
  {
    id: 7,
    title: "Hebergeur",
    description: "Projet de stage de première année de BTS SIO, Portail de connexion / tunnel d'achat réalisé en php (Veille sur Solidity et React pour implémenter le payement par smartcontract)",
    date: "Juin 2022",
    time: "20h",
    buttonText: "En savoir plus",
    group: 'travail en groupe',
    resp: 'Responsive',
    techno: 'PHP / HTML / CSS / SOLIDITY / REACT',
    icon: "work",
    image: {
        src1: '',
        src2: '',
        src3: ''
    },
    cardIcon: '/images/hebergeur/icon.png',
  },
  {
    id: 8,
    title: "Theme Sombre JS",
    description: "Une simple page réaliser en JS pour créer un systeme de theme sombre.",
    date: "Juillet 2022",
    time: "1h",
    buttonText: "En savoir plus",
    group: 'travail Individuelle',
    resp: 'Responsive',
    techno: 'JS / HTML / CSS',
    icon: "work",
    image: {
        src1: '/images/themesombre/1.png',
        src2: '/images/themesombre/2.png'
    },
    cardIcon: '/images/themesombre/icon.png',
  },
  {
    id: 9,
    title: "API prix Eth",
    description: "Une simple page réaliser en JS pour récuperer le prix de l'eth en temps réel grace a une api",
    date: "Juillet 2022",
    time: "30m",
    buttonText: "En savoir plus",
    group: 'travail Individuelle',
    resp: 'Responsive',
    techno: 'API / JS / HTML / CSS',
    icon: "work",
    image: {
        src1: '/images/eth/1.png'
    },
    cardIcon: '/images/eth/icon.png',
  },
  {
    id: 10,
    title: "Le Juste Prix",
    description: "Jeux inspiré du juste prix réaliser en JS",
    date: "Juillet 2022",
    time: "2h",
    buttonText: "En savoir plus",
    group: 'travail Individuelle',
    resp: 'Responsive',
    techno: 'JS / HTML / CSS',
    icon: "work",
    image: {
        src1: '/images/justeprix/1.png',
    },
    cardIcon: '/images/justeprix/icon.png',
  },
  {
    id: 11,
    title: "Meteo",
    description: "Projet Application web meteo en fonction d'un position géographique (API)",
    date: "Juillet 2022",
    time: "2h",
    buttonText: "En savoir plus",
    group: 'travail Individuelle',
    resp: 'Responsive',
    techno: 'JS / API / HTML / CSS',
    icon: "work",
    image: {
        src1: '/images/meteo/1.png',
        src2: '/images/meteo/2.png',
    },
    cardIcon: '/images/meteo/icon.png',
  },
  {
    id: 12,
    title: "Prévisualisateur de markdown",
    description: "Projet prévisualisateur de markdown réaliser en react pendant mon apprentissage en autodidacte",
    date: "Aout 2022",
    time: "2h",
    buttonText: "En savoir plus",
    group: 'travail Individuelle',
    resp: 'Pas responsive',
    techno: 'REACT / HTML / CSS',
    icon: "work",
    image: {
        src1: '/images/markdown/1.png'
    },
    cardIcon: '/images/markdown/icon.png',
  },
  {
    id: 13,
    title: "To do list",
    description: "Une To Do List réaliser en JS et Firebase / Axios",
    date: "Juillet 2022",
    time: "2h",
    buttonText: "En savoir plus",
    group: 'travail Individuelle',
    resp: 'Responsive',
    techno: 'JS / HTML / CSS',
    icon: "work",
    image: {
        src1: '/images/todo/1.png'
    },
    cardIcon: '/images/todo/icon.png',
  },
  
  
]

export default projectContent